# Generated by Django 5.2.17 on 2026-09-25 07:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingScheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="Основная схема", max_length=200)),
                (
                    "course_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_scheme",
                        to="courses.courseversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GradingComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ASSIGNMENTS", "Assignments"),
                            ("TESTS", "Tests"),
                            ("FINAL", "Final"),
                        ],
                        max_length=20,
                    ),
                ),
                ("weight", models.PositiveIntegerField()),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="grading.gradingscheme",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scheme", "kind"), name="grading_component_kind"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weight__gt", 0), ("weight__lte", 100)),
                        name="valid_component_weight",
                    ),
                ],
            },
        ),
    ]
