# Generated by Django 5.2.17 on 2026-09-30 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("RESUBMITTED", "Resubmitted"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("REVISION_REQUESTED", "Revision Requested"),
                    ("GRADED", "Graded"),
                ],
                db_index=True,
                default="SUBMITTED",
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "SUBMITTED",
                            "RESUBMITTED",
                            "UNDER_REVIEW",
                            "REVISION_REQUESTED",
                            "GRADED",
                        ],
                    )
                ),
                name="assignments_submission_state",
            ),
        ),
    ]
