# Generated by Django 5.2.17 on 2026-09-25 07:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("SINGLE_CHOICE", "Single"), ("MULTIPLE_CHOICE", "Multiple")],
                        max_length=30,
                    ),
                ),
                ("score", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField(default=0)),
                ("explanation", models.TextField(blank=True)),
                ("source_chunks", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="testing.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("max_score", models.PositiveIntegerField(default=100)),
                ("time_limit_minutes", models.PositiveIntegerField(default=30)),
                ("max_attempts", models.PositiveIntegerField(default=2)),
                ("shuffle_questions", models.BooleanField(default=True)),
                ("shuffle_answers", models.BooleanField(default=True)),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                ("passing_score", models.PositiveIntegerField(default=50)),
                ("status", models.CharField(default="DRAFT", max_length=20)),
                ("is_required", models.BooleanField(default=True)),
                ("is_final", models.BooleanField(default=False)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="courses.topic",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="testing.test",
            ),
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveIntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(null=True)),
                ("status", models.CharField(default="IN_PROGRESS", max_length=20)),
                ("score", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("question_order", models.JSONField(default=list)),
                ("option_order", models.JSONField(default=dict)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="testing.test",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("selected_options", models.JSONField(default=list)),
                ("answered_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="testing.question"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="testing.testattempt",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="test",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_attempts__gt", 0),
                    ("max_score__gt", 0),
                    ("passing_score__lte", 100),
                    ("time_limit_minutes__gt", 0),
                ),
                name="valid_test_limits",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gt", 0)), name="question_score_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="testattempt",
            constraint=models.UniqueConstraint(
                fields=("test", "student", "attempt_number"), name="test_attempt_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="testattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "IN_PROGRESS")),
                fields=("test", "student"),
                name="one_active_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="testattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("score__isnull", True),
                    models.Q(("score__gte", 0), ("score__lte", 100)),
                    _connector="OR",
                ),
                name="test_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="testanswer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="attempt_answer"
            ),
        ),
    ]
