# Generated by Django 5.2.17 on 2026-09-30 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="testattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("GRADED", "Graded"),
                    ("EXPIRED", "Expired"),
                ],
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="testattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["IN_PROGRESS", "GRADED", "EXPIRED"])),
                name="testing_testattempt_state",
            ),
        ),
    ]
