# Generated by Django 5.2.17 on 2026-09-30 08:22

from django.db import migrations, models


def classify_existing(apps, schema_editor):
    outbox = apps.get_model("notifications", "MailOutbox").objects.using(
        schema_editor.connection.alias
    )
    outbox.update(cycle_attempts=models.F("attempts"))
    outbox.filter(sent_at__isnull=False).update(status="SENT", encrypted_payload="")
    outbox.filter(sent_at__isnull=True, attempts__gte=5).update(
        status="FAILED", error_code="LEGACY_RETRIES_EXHAUSTED"
    )


def preserve_legacy_limit(apps, schema_editor):
    outbox = apps.get_model("notifications", "MailOutbox").objects.using(
        schema_editor.connection.alias
    )
    # Old workers must not silently resend exhausted or actively claimed mail.
    outbox.filter(status__in=["FAILED", "SENDING"]).update(attempts=5)


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailoutbox",
            name="cycle_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mailoutbox",
            name="error_code",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="mailoutbox",
            name="lease_token",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="mailoutbox",
            name="lease_until",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="mailoutbox",
            name="next_retry_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="mailoutbox",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENDING", "Sending"),
                    ("RETRY", "Retry"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.RunPython(classify_existing, preserve_legacy_limit),
        migrations.AddConstraint(
            model_name="mailoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING", "SENDING", "RETRY", "SENT", "FAILED"])
                ),
                name="mail_valid_status",
            ),
        ),
    ]
