# Generated by Django 5.2.17 on 2026-09-25 07:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("enrollments", "0001_initial"),
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="enrollments.enrollment"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="courses.topic"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("enrollment", "topic"), name="topic_completion")
                ],
            },
        ),
    ]
