# Generated by Django 5.2.17 on 2026-09-30 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_initial"),
        ("courses", "0002_state_invariants"),
        ("enrollments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("ARCHIVED", "Archived"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="ASSIGNED",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["ASSIGNED", "IN_PROGRESS", "COMPLETED", "ARCHIVED", "FAILED"])
                ),
                name="enrollments_enrollment_state",
            ),
        ),
    ]
