# Generated by Django 5.2.17 on 2026-10-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollments", "0002_state_invariants"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="access_revoked",
            field=models.BooleanField(default=False),
        ),
    ]
