# Generated by Django 5.2.17 on 2026-09-25 07:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=80)),
                ("language", models.CharField(choices=[("ru", "RU"), ("kk", "KZ")], max_length=2)),
                ("title", models.CharField(max_length=240)),
                ("body", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "language"), name="localized_content_key"
                    )
                ],
            },
        ),
    ]
