# Generated by Django 5.2.17 on 2026-09-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIBudgetDay",
            fields=[
                ("day", models.DateField(primary_key=True, serialize=False)),
                ("reserved_usd", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
            ],
        ),
    ]
