# Generated by Django 5.2.17 on 2026-09-30 08:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def retire_legacy_jobs(apps, schema_editor):
    # Deployment must stop old workers first. An old PROCESSING job may have
    # incurred provider cost, so neither it nor an unsnapshotted job is replayed.
    jobs = apps.get_model("ai", "AIJob").objects.using(schema_editor.connection.alias)
    jobs.filter(status__in=["QUEUED", "PROCESSING"]).update(
        status="FAILED",
        current_step="FAILED",
        error="LEGACY_OUTCOME_UNCERTAIN",
        finished_at=timezone.now(),
    )


def recover_legacy_sources(apps, schema_editor):
    sources = apps.get_model("ai", "SourceDocument").objects.using(schema_editor.connection.alias)
    deliveries = apps.get_model("ai", "TaskDelivery").objects.using(schema_editor.connection.alias)
    for source in sources.filter(processing_status__in=["QUEUED", "PROCESSING"]).iterator():
        source.processing_status = "QUEUED"
        source.save(update_fields=["processing_status"])
        deliveries.create(source_id=source.pk)


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_aibudgetday"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="PENDING", max_length=15)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("executions", models.PositiveIntegerField(default=0)),
                ("lease_token", models.UUIDField(null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                ("heartbeat_at", models.DateTimeField(null=True)),
                ("next_retry_at", models.DateTimeField(null=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="aijob",
            name="provider_started_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="aijob",
            name="source_snapshot",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="aiusagelog",
            name="job",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usage",
                to="ai.aijob",
            ),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="excluded",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(retire_legacy_jobs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="aijob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["QUEUED", "PROCESSING"])),
                fields=("course",),
                name="one_active_generation_per_course",
            ),
        ),
        migrations.AddField(
            model_name="taskdelivery",
            name="job",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery",
                to="ai.aijob",
            ),
        ),
        migrations.AddField(
            model_name="taskdelivery",
            name="source",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery",
                to="ai.sourcedocument",
            ),
        ),
        migrations.RunPython(recover_legacy_sources, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="taskdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("job__isnull", True), ("source__isnull", False)),
                    models.Q(("job__isnull", False), ("source__isnull", True)),
                    _connector="OR",
                ),
                name="delivery_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "PENDING",
                            "DISPATCHING",
                            "SENT",
                            "RUNNING",
                            "DONE",
                            "FAILED",
                            "CANCELLED",
                        ],
                    )
                ),
                name="delivery_valid_status",
            ),
        ),
    ]
