# Generated by Django 5.2.17 on 2026-09-30 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0003_durable_generation"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="aijob",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="QUEUED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="QUEUED",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="aijob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["QUEUED", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED"])
                ),
                name="ai_aijob_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("processing_status__in", ["QUEUED", "PROCESSING", "COMPLETED", "FAILED"])
                ),
                name="ai_sourcedocument_state",
            ),
        ),
    ]
