# Generated by Django 5.2.17 on 2026-09-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0004_state_invariants"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdelivery",
            name="request_id",
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
