# Generated by Django 5.2.17 on 2026-09-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="mime_type",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="material",
            name="size",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
