# Generated by Django 5.2.17 on 2026-09-30 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_teacher_ownership(apps, schema_editor):
    user = apps.get_model("accounts", "User")
    user.objects.using(schema_editor.connection.alias).filter(
        role="STUDENT", created_by__role="TEACHER"
    ).update(owner_teacher_id=models.F("created_by_id"))


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_managers"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="owner_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role", "STUDENT"), ("owner_teacher__isnull", True), _connector="OR"
                ),
                name="only_student_has_owner",
            ),
        ),
        migrations.RunPython(copy_teacher_ownership, migrations.RunPython.noop),
    ]
