# Generated by Django 5.2.17 on 2026-09-30 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published"), ("ARCHIVED", "Archived")],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="courseversion",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("REVIEW", "Review"), ("PUBLISHED", "Published")],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["DRAFT", "PUBLISHED", "ARCHIVED"])),
                name="courses_course_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["DRAFT", "REVIEW", "PUBLISHED"])),
                name="courses_courseversion_state",
            ),
        ),
    ]
